//! Player collection state and initialization.
//!
//! Provides thread-safe storage for players using Mutex and initializes
//! the collection with Argentina national team player data.

use crate::models::player::Player;
use std::sync::Mutex;

/// Thread-safe player collection type
pub type PlayerCollection = Mutex<Vec<Player>>;

/// Initialize players with Argentina national team data.
///
/// Creates a typed collection of 26 players from the Argentina squad,
/// eliminating the need for external JSON file loading.
pub fn initialize_players() -> Vec<Player> {
    vec![
        Player {
            id: 1,
            first_name: "Damián".to_string(),
            middle_name: "Emiliano".to_string(),
            last_name: "Martínez".to_string(),
            date_of_birth: "1992-09-02T00:00:00.000Z".to_string(),
            squad_number: 23,
            position: "Goalkeeper".to_string(),
            abbr_position: "GK".to_string(),
            team: "Aston Villa FC".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: 2,
            first_name: "Nahuel".to_string(),
            middle_name: "".to_string(),
            last_name: "Molina".to_string(),
            date_of_birth: "1998-04-06T00:00:00.000Z".to_string(),
            squad_number: 26,
            position: "Right-Back".to_string(),
            abbr_position: "RB".to_string(),
            team: "Atlético Madrid".to_string(),
            league: "La Liga".to_string(),
            starting11: true,
        },
        Player {
            id: 3,
            first_name: "Cristian".to_string(),
            middle_name: "Gabriel".to_string(),
            last_name: "Romero".to_string(),
            date_of_birth: "1998-04-27T00:00:00.000Z".to_string(),
            squad_number: 13,
            position: "Centre-Back".to_string(),
            abbr_position: "CB".to_string(),
            team: "Tottenham Hotspur".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: 4,
            first_name: "Nicolás".to_string(),
            middle_name: "Hernán Gonzalo".to_string(),
            last_name: "Otamendi".to_string(),
            date_of_birth: "1988-02-12T00:00:00.000Z".to_string(),
            squad_number: 19,
            position: "Centre-Back".to_string(),
            abbr_position: "CB".to_string(),
            team: "SL Benfica".to_string(),
            league: "Liga Portugal".to_string(),
            starting11: true,
        },
        Player {
            id: 5,
            first_name: "Nicolás".to_string(),
            middle_name: "Alejandro".to_string(),
            last_name: "Tagliafico".to_string(),
            date_of_birth: "1992-08-31T00:00:00.000Z".to_string(),
            squad_number: 3,
            position: "Left-Back".to_string(),
            abbr_position: "LB".to_string(),
            team: "Olympique Lyon".to_string(),
            league: "Ligue 1".to_string(),
            starting11: true,
        },
        Player {
            id: 6,
            first_name: "Ángel".to_string(),
            middle_name: "Fabián".to_string(),
            last_name: "Di María".to_string(),
            date_of_birth: "1988-02-14T00:00:00.000Z".to_string(),
            squad_number: 11,
            position: "Right Winger".to_string(),
            abbr_position: "RW".to_string(),
            team: "SL Benfica".to_string(),
            league: "Liga Portugal".to_string(),
            starting11: true,
        },
        Player {
            id: 7,
            first_name: "Rodrigo".to_string(),
            middle_name: "Javier".to_string(),
            last_name: "de Paul".to_string(),
            date_of_birth: "1994-05-24T00:00:00.000Z".to_string(),
            squad_number: 7,
            position: "Central Midfield".to_string(),
            abbr_position: "CM".to_string(),
            team: "Atlético Madrid".to_string(),
            league: "La Liga".to_string(),
            starting11: true,
        },
        Player {
            id: 8,
            first_name: "Enzo".to_string(),
            middle_name: "Jeremías".to_string(),
            last_name: "Fernández".to_string(),
            date_of_birth: "2001-01-17T00:00:00.000Z".to_string(),
            squad_number: 24,
            position: "Central Midfield".to_string(),
            abbr_position: "CM".to_string(),
            team: "Chelsea FC".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: 9,
            first_name: "Alexis".to_string(),
            middle_name: "".to_string(),
            last_name: "Mac Allister".to_string(),
            date_of_birth: "1998-12-24T00:00:00.000Z".to_string(),
            squad_number: 20,
            position: "Central Midfield".to_string(),
            abbr_position: "CM".to_string(),
            team: "Liverpool FC".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: 10,
            first_name: "Lionel".to_string(),
            middle_name: "Andrés".to_string(),
            last_name: "Messi".to_string(),
            date_of_birth: "1987-06-24T00:00:00.000Z".to_string(),
            squad_number: 10,
            position: "Right Winger".to_string(),
            abbr_position: "RW".to_string(),
            team: "Inter Miami CF".to_string(),
            league: "Major League Soccer".to_string(),
            starting11: true,
        },
        Player {
            id: 11,
            first_name: "Julián".to_string(),
            middle_name: "".to_string(),
            last_name: "Álvarez".to_string(),
            date_of_birth: "2000-01-31T00:00:00.000Z".to_string(),
            squad_number: 9,
            position: "Centre-Forward".to_string(),
            abbr_position: "CF".to_string(),
            team: "Manchester City".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: 12,
            first_name: "Franco".to_string(),
            middle_name: "Daniel".to_string(),
            last_name: "Armani".to_string(),
            date_of_birth: "1986-10-16T00:00:00.000Z".to_string(),
            squad_number: 1,
            position: "Goalkeeper".to_string(),
            abbr_position: "GK".to_string(),
            team: "River Plate".to_string(),
            league: "Copa de la Liga".to_string(),
            starting11: false,
        },
        Player {
            id: 13,
            first_name: "Gerónimo".to_string(),
            middle_name: "".to_string(),
            last_name: "Rulli".to_string(),
            date_of_birth: "1992-05-20T00:00:00.000Z".to_string(),
            squad_number: 12,
            position: "Goalkeeper".to_string(),
            abbr_position: "GK".to_string(),
            team: "Ajax Amsterdam".to_string(),
            league: "Eredivisie".to_string(),
            starting11: false,
        },
        Player {
            id: 14,
            first_name: "Juan".to_string(),
            middle_name: "Marcos".to_string(),
            last_name: "Foyth".to_string(),
            date_of_birth: "1998-01-12T00:00:00.000Z".to_string(),
            squad_number: 2,
            position: "Right-Back".to_string(),
            abbr_position: "RB".to_string(),
            team: "Villarreal".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: 15,
            first_name: "Gonzalo".to_string(),
            middle_name: "Ariel".to_string(),
            last_name: "Montiel".to_string(),
            date_of_birth: "1997-01-01T00:00:00.000Z".to_string(),
            squad_number: 4,
            position: "Right-Back".to_string(),
            abbr_position: "RB".to_string(),
            team: "Nottingham Forest".to_string(),
            league: "Premier League".to_string(),
            starting11: false,
        },
        Player {
            id: 16,
            first_name: "Germán".to_string(),
            middle_name: "Alejo".to_string(),
            last_name: "Pezzella".to_string(),
            date_of_birth: "1991-06-27T00:00:00.000Z".to_string(),
            squad_number: 6,
            position: "Centre-Back".to_string(),
            abbr_position: "CB".to_string(),
            team: "Real Betis Balompié".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: 17,
            first_name: "Marcos".to_string(),
            middle_name: "Javier".to_string(),
            last_name: "Acuña".to_string(),
            date_of_birth: "1991-10-28T00:00:00.000Z".to_string(),
            squad_number: 8,
            position: "Left-Back".to_string(),
            abbr_position: "LB".to_string(),
            team: "Sevilla FC".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: 18,
            first_name: "Lisandro".to_string(),
            middle_name: "".to_string(),
            last_name: "Martínez".to_string(),
            date_of_birth: "1998-01-18T00:00:00.000Z".to_string(),
            squad_number: 25,
            position: "Centre-Back".to_string(),
            abbr_position: "CB".to_string(),
            team: "Manchester United".to_string(),
            league: "Premier League".to_string(),
            starting11: false,
        },
        Player {
            id: 19,
            first_name: "Leandro".to_string(),
            middle_name: "Daniel".to_string(),
            last_name: "Paredes".to_string(),
            date_of_birth: "1994-06-29T00:00:00.000Z".to_string(),
            squad_number: 5,
            position: "Defensive Midfield".to_string(),
            abbr_position: "DM".to_string(),
            team: "AS Roma".to_string(),
            league: "Serie A".to_string(),
            starting11: false,
        },
        Player {
            id: 20,
            first_name: "Exequiel".to_string(),
            middle_name: "Alejandro".to_string(),
            last_name: "Palacios".to_string(),
            date_of_birth: "1998-10-05T00:00:00.000Z".to_string(),
            squad_number: 14,
            position: "Central Midfield".to_string(),
            abbr_position: "CM".to_string(),
            team: "Bayer 04 Leverkusen".to_string(),
            league: "Bundesliga".to_string(),
            starting11: false,
        },
        Player {
            id: 21,
            first_name: "Alejandro".to_string(),
            middle_name: "Darío".to_string(),
            last_name: "Gómez".to_string(),
            date_of_birth: "1988-02-15T00:00:00.000Z".to_string(),
            squad_number: 17,
            position: "Left Winger".to_string(),
            abbr_position: "LW".to_string(),
            team: "AC Monza".to_string(),
            league: "Serie A".to_string(),
            starting11: false,
        },
        Player {
            id: 22,
            first_name: "Guido".to_string(),
            middle_name: "".to_string(),
            last_name: "Rodríguez".to_string(),
            date_of_birth: "1994-04-12T00:00:00.000Z".to_string(),
            squad_number: 18,
            position: "Defensive Midfield".to_string(),
            abbr_position: "DM".to_string(),
            team: "Real Betis Balompié".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: 23,
            first_name: "Ángel".to_string(),
            middle_name: "Martín".to_string(),
            last_name: "Correa".to_string(),
            date_of_birth: "1995-03-09T00:00:00.000Z".to_string(),
            squad_number: 15,
            position: "Right Winger".to_string(),
            abbr_position: "RW".to_string(),
            team: "Atlético Madrid".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: 24,
            first_name: "Thiago".to_string(),
            middle_name: "Ezequiel".to_string(),
            last_name: "Almada".to_string(),
            date_of_birth: "2001-04-26T00:00:00.000Z".to_string(),
            squad_number: 16,
            position: "Attacking Midfield".to_string(),
            abbr_position: "AM".to_string(),
            team: "Atlanta United FC".to_string(),
            league: "Major League Soccer".to_string(),
            starting11: false,
        },
        Player {
            id: 25,
            first_name: "Paulo".to_string(),
            middle_name: "Exequiel".to_string(),
            last_name: "Dybala".to_string(),
            date_of_birth: "1993-11-15T00:00:00.000Z".to_string(),
            squad_number: 21,
            position: "Second Striker".to_string(),
            abbr_position: "SS".to_string(),
            team: "AS Roma".to_string(),
            league: "Serie A".to_string(),
            starting11: false,
        },
        Player {
            id: 26,
            first_name: "Lautaro".to_string(),
            middle_name: "Javier".to_string(),
            last_name: "Martínez".to_string(),
            date_of_birth: "1997-08-22T00:00:00.000Z".to_string(),
            squad_number: 22,
            position: "Centre-Forward".to_string(),
            abbr_position: "CF".to_string(),
            team: "Inter Milan".to_string(),
            league: "Serie A".to_string(),
            starting11: false,
        },
    ]
}
