//! Thread-safe player collection state and seed data.
//!
//! Provides the storage type used across the whole application and seeds it
//! with the Argentina 2022 World Cup squad at startup.

use crate::models::player::Player;
use std::sync::Mutex;

/// Thread-safe player collection.
///
/// A type alias for `Mutex<Vec<Player>>`. Rocket shares application state
/// across multiple async worker threads to handle concurrent requests.
/// Wrapping the `Vec<Player>` in a [`std::sync::Mutex`] ensures that only
/// one thread can read or modify the collection at a time, preventing data
/// races.
///
/// ## Rust note: locking and `MutexGuard`
/// Before accessing the inner `Vec`, callers must call `.lock()`:
/// ```ignore
/// let players = state.lock().map_err(|_| Status::InternalServerError)?;
/// ```
/// `lock()` blocks the current thread until no other thread holds the lock,
/// then returns a `MutexGuard<Vec<Player>>`. The guard releases the lock
/// automatically when it goes out of scope — this is the RAII pattern
/// (Resource Acquisition Is Initialization), a core Rust idiom for
/// deterministic resource cleanup without a garbage collector.
pub type PlayerCollection = Mutex<Vec<Player>>;

/// Seeds the player collection with the Argentina 2022 World Cup squad (26 players).
///
/// Called once at startup in [`main`](crate). Returns a plain `Vec<Player>`,
/// which is then wrapped in a [`PlayerCollection`] (i.e. `Mutex`) before
/// being handed to Rocket's state management via `.manage()`.
///
/// ## Rust note: `to_string()`
/// String *literals* (`&str`, e.g. `"Martínez"`) are static references to
/// read-only data baked into the binary. `.to_string()` allocates a new
/// heap-owned `String`, which is required because the `Player` struct
/// fields must own their data independently of the literal's lifetime.
pub fn initialize_players() -> Vec<Player> {
    vec![
        Player {
            id: "01772c59-43f0-5d85-b913-c78e4e281452".to_string(),
            first_name: "Damián".to_string(),
            middle_name: "Emiliano".to_string(),
            last_name: "Martínez".to_string(),
            date_of_birth: "1992-09-02T00:00:00.000Z".to_string(),
            squad_number: 23,
            position: "Goalkeeper".to_string(),
            abbr_position: "GK".to_string(),
            team: "Aston Villa FC".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: "da31293b-4c7e-5e0f-a168-469ee29ecbc4".to_string(),
            first_name: "Nahuel".to_string(),
            middle_name: "".to_string(),
            last_name: "Molina".to_string(),
            date_of_birth: "1998-04-06T00:00:00.000Z".to_string(),
            squad_number: 26,
            position: "Right-Back".to_string(),
            abbr_position: "RB".to_string(),
            team: "Atlético Madrid".to_string(),
            league: "La Liga".to_string(),
            starting11: true,
        },
        Player {
            id: "c096c69e-762b-5281-9290-bb9c167a24a0".to_string(),
            first_name: "Cristian".to_string(),
            middle_name: "Gabriel".to_string(),
            last_name: "Romero".to_string(),
            date_of_birth: "1998-04-27T00:00:00.000Z".to_string(),
            squad_number: 13,
            position: "Centre-Back".to_string(),
            abbr_position: "CB".to_string(),
            team: "Tottenham Hotspur".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: "d5f7dd7a-1dcb-5960-ba27-e34865b63358".to_string(),
            first_name: "Nicolás".to_string(),
            middle_name: "Hernán Gonzalo".to_string(),
            last_name: "Otamendi".to_string(),
            date_of_birth: "1988-02-12T00:00:00.000Z".to_string(),
            squad_number: 19,
            position: "Centre-Back".to_string(),
            abbr_position: "CB".to_string(),
            team: "SL Benfica".to_string(),
            league: "Liga Portugal".to_string(),
            starting11: true,
        },
        Player {
            id: "2f6f90a0-9b9d-5023-96d2-a2aaf03143a6".to_string(),
            first_name: "Nicolás".to_string(),
            middle_name: "Alejandro".to_string(),
            last_name: "Tagliafico".to_string(),
            date_of_birth: "1992-08-31T00:00:00.000Z".to_string(),
            squad_number: 3,
            position: "Left-Back".to_string(),
            abbr_position: "LB".to_string(),
            team: "Olympique Lyon".to_string(),
            league: "Ligue 1".to_string(),
            starting11: true,
        },
        Player {
            id: "b5b46e79-929e-5ed2-949d-0d167109c022".to_string(),
            first_name: "Ángel".to_string(),
            middle_name: "Fabián".to_string(),
            last_name: "Di María".to_string(),
            date_of_birth: "1988-02-14T00:00:00.000Z".to_string(),
            squad_number: 11,
            position: "Right Winger".to_string(),
            abbr_position: "RW".to_string(),
            team: "SL Benfica".to_string(),
            league: "Liga Portugal".to_string(),
            starting11: true,
        },
        Player {
            id: "0293b282-1da8-562e-998e-83849b417a42".to_string(),
            first_name: "Rodrigo".to_string(),
            middle_name: "Javier".to_string(),
            last_name: "de Paul".to_string(),
            date_of_birth: "1994-05-24T00:00:00.000Z".to_string(),
            squad_number: 7,
            position: "Central Midfield".to_string(),
            abbr_position: "CM".to_string(),
            team: "Atlético Madrid".to_string(),
            league: "La Liga".to_string(),
            starting11: true,
        },
        Player {
            id: "d3ba552a-dac3-588a-b961-1ea7224017fd".to_string(),
            first_name: "Enzo".to_string(),
            middle_name: "Jeremías".to_string(),
            last_name: "Fernández".to_string(),
            date_of_birth: "2001-01-17T00:00:00.000Z".to_string(),
            squad_number: 24,
            position: "Central Midfield".to_string(),
            abbr_position: "CM".to_string(),
            team: "SL Benfica".to_string(),
            league: "Liga Portugal".to_string(),
            starting11: true,
        },
        Player {
            id: "9613cae9-16ab-5b54-937e-3135123b9e0d".to_string(),
            first_name: "Alexis".to_string(),
            middle_name: "".to_string(),
            last_name: "Mac Allister".to_string(),
            date_of_birth: "1998-12-24T00:00:00.000Z".to_string(),
            squad_number: 20,
            position: "Central Midfield".to_string(),
            abbr_position: "CM".to_string(),
            team: "Brighton & Hove Albion".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: "acc433bf-d505-51fe-831e-45eb44c4d43c".to_string(),
            first_name: "Lionel".to_string(),
            middle_name: "Andrés".to_string(),
            last_name: "Messi".to_string(),
            date_of_birth: "1987-06-24T00:00:00.000Z".to_string(),
            squad_number: 10,
            position: "Right Winger".to_string(),
            abbr_position: "RW".to_string(),
            team: "Paris Saint-Germain".to_string(),
            league: "Ligue 1".to_string(),
            starting11: true,
        },
        Player {
            id: "38bae91d-8519-55a2-b30a-b9fe38849bfb".to_string(),
            first_name: "Julián".to_string(),
            middle_name: "".to_string(),
            last_name: "Álvarez".to_string(),
            date_of_birth: "2000-01-31T00:00:00.000Z".to_string(),
            squad_number: 9,
            position: "Centre-Forward".to_string(),
            abbr_position: "CF".to_string(),
            team: "Manchester City".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: "5a9cd988-95e6-54c1-bc34-9aa08acca8d0".to_string(),
            first_name: "Franco".to_string(),
            middle_name: "Daniel".to_string(),
            last_name: "Armani".to_string(),
            date_of_birth: "1986-10-16T00:00:00.000Z".to_string(),
            squad_number: 1,
            position: "Goalkeeper".to_string(),
            abbr_position: "GK".to_string(),
            team: "River Plate".to_string(),
            league: "Copa de la Liga".to_string(),
            starting11: false,
        },
        Player {
            id: "c62f2ac1-41e8-5d34-b073-2ba0913d0e31".to_string(),
            first_name: "Gerónimo".to_string(),
            middle_name: "".to_string(),
            last_name: "Rulli".to_string(),
            date_of_birth: "1992-05-20T00:00:00.000Z".to_string(),
            squad_number: 12,
            position: "Goalkeeper".to_string(),
            abbr_position: "GK".to_string(),
            team: "Ajax Amsterdam".to_string(),
            league: "Eredivisie".to_string(),
            starting11: false,
        },
        Player {
            id: "5fdb10e8-38c0-5084-9a3f-b369a960b9c2".to_string(),
            first_name: "Juan".to_string(),
            middle_name: "Marcos".to_string(),
            last_name: "Foyth".to_string(),
            date_of_birth: "1998-01-12T00:00:00.000Z".to_string(),
            squad_number: 2,
            position: "Right-Back".to_string(),
            abbr_position: "RB".to_string(),
            team: "Villarreal".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: "bbd441f7-fcfb-5834-8468-2a9004b64c8c".to_string(),
            first_name: "Gonzalo".to_string(),
            middle_name: "Ariel".to_string(),
            last_name: "Montiel".to_string(),
            date_of_birth: "1997-01-01T00:00:00.000Z".to_string(),
            squad_number: 4,
            position: "Right-Back".to_string(),
            abbr_position: "RB".to_string(),
            team: "Nottingham Forest".to_string(),
            league: "Premier League".to_string(),
            starting11: false,
        },
        Player {
            id: "d8bfea25-f189-5d5e-b3a5-ed89329b9f7c".to_string(),
            first_name: "Germán".to_string(),
            middle_name: "Alejo".to_string(),
            last_name: "Pezzella".to_string(),
            date_of_birth: "1991-06-27T00:00:00.000Z".to_string(),
            squad_number: 6,
            position: "Centre-Back".to_string(),
            abbr_position: "CB".to_string(),
            team: "Real Betis Balompié".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: "dca343a8-12e5-53d6-89a8-916b120a5ee4".to_string(),
            first_name: "Marcos".to_string(),
            middle_name: "Javier".to_string(),
            last_name: "Acuña".to_string(),
            date_of_birth: "1991-10-28T00:00:00.000Z".to_string(),
            squad_number: 8,
            position: "Left-Back".to_string(),
            abbr_position: "LB".to_string(),
            team: "Sevilla FC".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: "98306555-a466-5d18-804e-dc82175e697b".to_string(),
            first_name: "Lisandro".to_string(),
            middle_name: "".to_string(),
            last_name: "Martínez".to_string(),
            date_of_birth: "1998-01-18T00:00:00.000Z".to_string(),
            squad_number: 25,
            position: "Centre-Back".to_string(),
            abbr_position: "CB".to_string(),
            team: "Manchester United".to_string(),
            league: "Premier League".to_string(),
            starting11: false,
        },
        Player {
            id: "9d140400-196f-55d8-86e1-e0b96a375c83".to_string(),
            first_name: "Leandro".to_string(),
            middle_name: "Daniel".to_string(),
            last_name: "Paredes".to_string(),
            date_of_birth: "1994-06-29T00:00:00.000Z".to_string(),
            squad_number: 5,
            position: "Defensive Midfield".to_string(),
            abbr_position: "DM".to_string(),
            team: "AS Roma".to_string(),
            league: "Serie A".to_string(),
            starting11: false,
        },
        Player {
            id: "d3b0e8e8-2c34-531a-b608-b24fed0ef986".to_string(),
            first_name: "Exequiel".to_string(),
            middle_name: "Alejandro".to_string(),
            last_name: "Palacios".to_string(),
            date_of_birth: "1998-10-05T00:00:00.000Z".to_string(),
            squad_number: 14,
            position: "Central Midfield".to_string(),
            abbr_position: "CM".to_string(),
            team: "Bayer 04 Leverkusen".to_string(),
            league: "Bundesliga".to_string(),
            starting11: false,
        },
        Player {
            id: "7cc8d527-56a2-58bd-9528-2618fc139d30".to_string(),
            first_name: "Alejandro".to_string(),
            middle_name: "Darío".to_string(),
            last_name: "Gómez".to_string(),
            date_of_birth: "1988-02-15T00:00:00.000Z".to_string(),
            squad_number: 17,
            position: "Left Winger".to_string(),
            abbr_position: "LW".to_string(),
            team: "AC Monza".to_string(),
            league: "Serie A".to_string(),
            starting11: false,
        },
        Player {
            id: "191c82af-0c51-526a-b903-c3600b61b506".to_string(),
            first_name: "Guido".to_string(),
            middle_name: "".to_string(),
            last_name: "Rodríguez".to_string(),
            date_of_birth: "1994-04-12T00:00:00.000Z".to_string(),
            squad_number: 18,
            position: "Defensive Midfield".to_string(),
            abbr_position: "DM".to_string(),
            team: "Real Betis Balompié".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: "b1306b7b-a3a4-5f7c-90fd-dd5bdbed57ba".to_string(),
            first_name: "Ángel".to_string(),
            middle_name: "Martín".to_string(),
            last_name: "Correa".to_string(),
            date_of_birth: "1995-03-09T00:00:00.000Z".to_string(),
            squad_number: 15,
            position: "Right Winger".to_string(),
            abbr_position: "RW".to_string(),
            team: "Atlético Madrid".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: "ecec27e8-487b-5622-b116-0855020477ed".to_string(),
            first_name: "Thiago".to_string(),
            middle_name: "Ezequiel".to_string(),
            last_name: "Almada".to_string(),
            date_of_birth: "2001-04-26T00:00:00.000Z".to_string(),
            squad_number: 16,
            position: "Attacking Midfield".to_string(),
            abbr_position: "AM".to_string(),
            team: "Atlanta United FC".to_string(),
            league: "Major League Soccer".to_string(),
            starting11: false,
        },
        Player {
            id: "7941cd7c-4df1-5952-97e8-1e7f5d08e8aa".to_string(),
            first_name: "Paulo".to_string(),
            middle_name: "Exequiel".to_string(),
            last_name: "Dybala".to_string(),
            date_of_birth: "1993-11-15T00:00:00.000Z".to_string(),
            squad_number: 21,
            position: "Second Striker".to_string(),
            abbr_position: "SS".to_string(),
            team: "AS Roma".to_string(),
            league: "Serie A".to_string(),
            starting11: false,
        },
        Player {
            id: "79c96f29-c59f-5f98-96b8-3a5946246624".to_string(),
            first_name: "Lautaro".to_string(),
            middle_name: "Javier".to_string(),
            last_name: "Martínez".to_string(),
            date_of_birth: "1997-08-22T00:00:00.000Z".to_string(),
            squad_number: 22,
            position: "Centre-Forward".to_string(),
            abbr_position: "CF".to_string(),
            team: "Inter Milan".to_string(),
            league: "Serie A".to_string(),
            starting11: false,
        },
    ]
}
