//! Thread-safe player collection state and seed data.
//!
//! Provides the storage type used across the whole application and seeds it
//! with the Argentina 2022 World Cup squad at startup.

use crate::models::player::Player;
use std::sync::Mutex;

/// Thread-safe player collection.
///
/// A type alias for `Mutex<Vec<Player>>`. Rocket shares application state
/// across multiple async worker threads to handle concurrent requests.
/// Wrapping the `Vec<Player>` in a [`std::sync::Mutex`] ensures that only
/// one thread can read or modify the collection at a time, preventing data
/// races.
///
/// ## Rust note: locking and `MutexGuard`
/// Before accessing the inner `Vec`, callers must call `.lock()`:
/// ```ignore
/// let players = state.lock().map_err(|_| Status::InternalServerError)?;
/// ```
/// `lock()` blocks the current thread until no other thread holds the lock,
/// then returns a `MutexGuard<Vec<Player>>`. The guard releases the lock
/// automatically when it goes out of scope — this is the RAII pattern
/// (Resource Acquisition Is Initialization), a core Rust idiom for
/// deterministic resource cleanup without a garbage collector.
pub type PlayerCollection = Mutex<Vec<Player>>;

/// Seeds the player collection with the Argentina 2022 World Cup squad (26 players).
///
/// Called once at startup in [`main`](crate). Returns a plain `Vec<Player>`,
/// which is then wrapped in a [`PlayerCollection`] (i.e. `Mutex`) before
/// being handed to Rocket's state management via `.manage()`.
///
/// ## Rust note: `to_string()`
/// String *literals* (`&str`, e.g. `"Martínez"`) are static references to
/// read-only data baked into the binary. `.to_string()` allocates a new
/// heap-owned `String`, which is required because the `Player` struct
/// fields must own their data independently of the literal's lifetime.
pub fn initialize_players() -> Vec<Player> {
    vec![
        Player {
            id: "f28c863b-48fd-4f41-834f-e49ee16d048a".to_string(),
            first_name: "Damián".to_string(),
            middle_name: "Emiliano".to_string(),
            last_name: "Martínez".to_string(),
            date_of_birth: "1992-09-02T00:00:00.000Z".to_string(),
            squad_number: 23,
            position: "Goalkeeper".to_string(),
            abbr_position: "GK".to_string(),
            team: "Aston Villa FC".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: "45765a8a-78df-45ab-8d91-9d1a49d38d7a".to_string(),
            first_name: "Nahuel".to_string(),
            middle_name: "".to_string(),
            last_name: "Molina".to_string(),
            date_of_birth: "1998-04-06T00:00:00.000Z".to_string(),
            squad_number: 26,
            position: "Right-Back".to_string(),
            abbr_position: "RB".to_string(),
            team: "Atlético Madrid".to_string(),
            league: "La Liga".to_string(),
            starting11: true,
        },
        Player {
            id: "d3ab3b82-90c1-463f-ba71-78edf4b6cdce".to_string(),
            first_name: "Cristian".to_string(),
            middle_name: "Gabriel".to_string(),
            last_name: "Romero".to_string(),
            date_of_birth: "1998-04-27T00:00:00.000Z".to_string(),
            squad_number: 13,
            position: "Centre-Back".to_string(),
            abbr_position: "CB".to_string(),
            team: "Tottenham Hotspur".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: "cee9bb3e-3737-4d12-9f27-f3941be01642".to_string(),
            first_name: "Nicolás".to_string(),
            middle_name: "Hernán Gonzalo".to_string(),
            last_name: "Otamendi".to_string(),
            date_of_birth: "1988-02-12T00:00:00.000Z".to_string(),
            squad_number: 19,
            position: "Centre-Back".to_string(),
            abbr_position: "CB".to_string(),
            team: "SL Benfica".to_string(),
            league: "Liga Portugal".to_string(),
            starting11: true,
        },
        Player {
            id: "a98b2337-5f2e-4f93-b30f-0969b7ccde47".to_string(),
            first_name: "Nicolás".to_string(),
            middle_name: "Alejandro".to_string(),
            last_name: "Tagliafico".to_string(),
            date_of_birth: "1992-08-31T00:00:00.000Z".to_string(),
            squad_number: 3,
            position: "Left-Back".to_string(),
            abbr_position: "LB".to_string(),
            team: "Olympique Lyon".to_string(),
            league: "Ligue 1".to_string(),
            starting11: true,
        },
        Player {
            id: "1e9bcf7c-7cf0-4535-ab4f-2bec5c6777e3".to_string(),
            first_name: "Ángel".to_string(),
            middle_name: "Fabián".to_string(),
            last_name: "Di María".to_string(),
            date_of_birth: "1988-02-14T00:00:00.000Z".to_string(),
            squad_number: 11,
            position: "Right Winger".to_string(),
            abbr_position: "RW".to_string(),
            team: "SL Benfica".to_string(),
            league: "Liga Portugal".to_string(),
            starting11: true,
        },
        Player {
            id: "36980293-8dea-4f43-95ba-8067fa71591c".to_string(),
            first_name: "Rodrigo".to_string(),
            middle_name: "Javier".to_string(),
            last_name: "de Paul".to_string(),
            date_of_birth: "1994-05-24T00:00:00.000Z".to_string(),
            squad_number: 7,
            position: "Central Midfield".to_string(),
            abbr_position: "CM".to_string(),
            team: "Atlético Madrid".to_string(),
            league: "La Liga".to_string(),
            starting11: true,
        },
        Player {
            id: "fcf653d9-c74d-4757-adb2-dcf46cbc2825".to_string(),
            first_name: "Enzo".to_string(),
            middle_name: "Jeremías".to_string(),
            last_name: "Fernández".to_string(),
            date_of_birth: "2001-01-17T00:00:00.000Z".to_string(),
            squad_number: 24,
            position: "Central Midfield".to_string(),
            abbr_position: "CM".to_string(),
            team: "Chelsea FC".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: "5cd7d768-dde8-4037-90a6-50d541a98577".to_string(),
            first_name: "Alexis".to_string(),
            middle_name: "".to_string(),
            last_name: "Mac Allister".to_string(),
            date_of_birth: "1998-12-24T00:00:00.000Z".to_string(),
            squad_number: 20,
            position: "Central Midfield".to_string(),
            abbr_position: "CM".to_string(),
            team: "Liverpool FC".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: "f10f398d-b2ff-40aa-acac-51f58d129bc7".to_string(),
            first_name: "Lionel".to_string(),
            middle_name: "Andrés".to_string(),
            last_name: "Messi".to_string(),
            date_of_birth: "1987-06-24T00:00:00.000Z".to_string(),
            squad_number: 10,
            position: "Right Winger".to_string(),
            abbr_position: "RW".to_string(),
            team: "Inter Miami CF".to_string(),
            league: "Major League Soccer".to_string(),
            starting11: true,
        },
        Player {
            id: "80d61421-93a1-466c-82dc-81152b677c22".to_string(),
            first_name: "Julián".to_string(),
            middle_name: "".to_string(),
            last_name: "Álvarez".to_string(),
            date_of_birth: "2000-01-31T00:00:00.000Z".to_string(),
            squad_number: 9,
            position: "Centre-Forward".to_string(),
            abbr_position: "CF".to_string(),
            team: "Manchester City".to_string(),
            league: "Premier League".to_string(),
            starting11: true,
        },
        Player {
            id: "2c3ec9a0-a1b3-4e34-82e0-7413be4bc77f".to_string(),
            first_name: "Franco".to_string(),
            middle_name: "Daniel".to_string(),
            last_name: "Armani".to_string(),
            date_of_birth: "1986-10-16T00:00:00.000Z".to_string(),
            squad_number: 1,
            position: "Goalkeeper".to_string(),
            abbr_position: "GK".to_string(),
            team: "River Plate".to_string(),
            league: "Copa de la Liga".to_string(),
            starting11: false,
        },
        Player {
            id: "3f5dcba2-4b86-4704-a020-2f2c2a8875f8".to_string(),
            first_name: "Gerónimo".to_string(),
            middle_name: "".to_string(),
            last_name: "Rulli".to_string(),
            date_of_birth: "1992-05-20T00:00:00.000Z".to_string(),
            squad_number: 12,
            position: "Goalkeeper".to_string(),
            abbr_position: "GK".to_string(),
            team: "Ajax Amsterdam".to_string(),
            league: "Eredivisie".to_string(),
            starting11: false,
        },
        Player {
            id: "378e11b8-76b2-4886-b2c9-f686edaa7d5e".to_string(),
            first_name: "Juan".to_string(),
            middle_name: "Marcos".to_string(),
            last_name: "Foyth".to_string(),
            date_of_birth: "1998-01-12T00:00:00.000Z".to_string(),
            squad_number: 2,
            position: "Right-Back".to_string(),
            abbr_position: "RB".to_string(),
            team: "Villarreal".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: "f4daee32-549a-43cb-9214-20034bb00a7d".to_string(),
            first_name: "Gonzalo".to_string(),
            middle_name: "Ariel".to_string(),
            last_name: "Montiel".to_string(),
            date_of_birth: "1997-01-01T00:00:00.000Z".to_string(),
            squad_number: 4,
            position: "Right-Back".to_string(),
            abbr_position: "RB".to_string(),
            team: "Nottingham Forest".to_string(),
            league: "Premier League".to_string(),
            starting11: false,
        },
        Player {
            id: "ac5b20a4-96e5-45e2-9089-bcc5a37f93c0".to_string(),
            first_name: "Germán".to_string(),
            middle_name: "Alejo".to_string(),
            last_name: "Pezzella".to_string(),
            date_of_birth: "1991-06-27T00:00:00.000Z".to_string(),
            squad_number: 6,
            position: "Centre-Back".to_string(),
            abbr_position: "CB".to_string(),
            team: "Real Betis Balompié".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: "409d5d12-e993-4a40-9e73-c054a06565dc".to_string(),
            first_name: "Marcos".to_string(),
            middle_name: "Javier".to_string(),
            last_name: "Acuña".to_string(),
            date_of_birth: "1991-10-28T00:00:00.000Z".to_string(),
            squad_number: 8,
            position: "Left-Back".to_string(),
            abbr_position: "LB".to_string(),
            team: "Sevilla FC".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: "8f0b631f-f95d-40cc-8a59-61bbd82f6de5".to_string(),
            first_name: "Lisandro".to_string(),
            middle_name: "".to_string(),
            last_name: "Martínez".to_string(),
            date_of_birth: "1998-01-18T00:00:00.000Z".to_string(),
            squad_number: 25,
            position: "Centre-Back".to_string(),
            abbr_position: "CB".to_string(),
            team: "Manchester United".to_string(),
            league: "Premier League".to_string(),
            starting11: false,
        },
        Player {
            id: "d7a342b5-8e96-415b-9c97-c2f80dbc33b6".to_string(),
            first_name: "Leandro".to_string(),
            middle_name: "Daniel".to_string(),
            last_name: "Paredes".to_string(),
            date_of_birth: "1994-06-29T00:00:00.000Z".to_string(),
            squad_number: 5,
            position: "Defensive Midfield".to_string(),
            abbr_position: "DM".to_string(),
            team: "AS Roma".to_string(),
            league: "Serie A".to_string(),
            starting11: false,
        },
        Player {
            id: "e395e764-0140-4c41-a9bb-ced7652a64ae".to_string(),
            first_name: "Exequiel".to_string(),
            middle_name: "Alejandro".to_string(),
            last_name: "Palacios".to_string(),
            date_of_birth: "1998-10-05T00:00:00.000Z".to_string(),
            squad_number: 14,
            position: "Central Midfield".to_string(),
            abbr_position: "CM".to_string(),
            team: "Bayer 04 Leverkusen".to_string(),
            league: "Bundesliga".to_string(),
            starting11: false,
        },
        Player {
            id: "170b46d5-2a34-408d-8595-7aea1a047c0c".to_string(),
            first_name: "Alejandro".to_string(),
            middle_name: "Darío".to_string(),
            last_name: "Gómez".to_string(),
            date_of_birth: "1988-02-15T00:00:00.000Z".to_string(),
            squad_number: 17,
            position: "Left Winger".to_string(),
            abbr_position: "LW".to_string(),
            team: "AC Monza".to_string(),
            league: "Serie A".to_string(),
            starting11: false,
        },
        Player {
            id: "3fe5ca9c-5887-4432-8f8b-b60a1a93b626".to_string(),
            first_name: "Guido".to_string(),
            middle_name: "".to_string(),
            last_name: "Rodríguez".to_string(),
            date_of_birth: "1994-04-12T00:00:00.000Z".to_string(),
            squad_number: 18,
            position: "Defensive Midfield".to_string(),
            abbr_position: "DM".to_string(),
            team: "Real Betis Balompié".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: "79439ba4-5f97-441f-8612-f3957058f99c".to_string(),
            first_name: "Ángel".to_string(),
            middle_name: "Martín".to_string(),
            last_name: "Correa".to_string(),
            date_of_birth: "1995-03-09T00:00:00.000Z".to_string(),
            squad_number: 15,
            position: "Right Winger".to_string(),
            abbr_position: "RW".to_string(),
            team: "Atlético Madrid".to_string(),
            league: "La Liga".to_string(),
            starting11: false,
        },
        Player {
            id: "a9ebeb5f-3ca4-42f6-9a80-c723556e00fa".to_string(),
            first_name: "Thiago".to_string(),
            middle_name: "Ezequiel".to_string(),
            last_name: "Almada".to_string(),
            date_of_birth: "2001-04-26T00:00:00.000Z".to_string(),
            squad_number: 16,
            position: "Attacking Midfield".to_string(),
            abbr_position: "AM".to_string(),
            team: "Atlanta United FC".to_string(),
            league: "Major League Soccer".to_string(),
            starting11: false,
        },
        Player {
            id: "dcc142ca-2e76-49b6-b9d1-d7ae7d7110f2".to_string(),
            first_name: "Paulo".to_string(),
            middle_name: "Exequiel".to_string(),
            last_name: "Dybala".to_string(),
            date_of_birth: "1993-11-15T00:00:00.000Z".to_string(),
            squad_number: 21,
            position: "Second Striker".to_string(),
            abbr_position: "SS".to_string(),
            team: "AS Roma".to_string(),
            league: "Serie A".to_string(),
            starting11: false,
        },
        Player {
            id: "87a135a2-3634-49b9-b4b0-21a8b80f2b9d".to_string(),
            first_name: "Lautaro".to_string(),
            middle_name: "Javier".to_string(),
            last_name: "Martínez".to_string(),
            date_of_birth: "1997-08-22T00:00:00.000Z".to_string(),
            squad_number: 22,
            position: "Centre-Forward".to_string(),
            abbr_position: "CF".to_string(),
            team: "Inter Milan".to_string(),
            league: "Serie A".to_string(),
            starting11: false,
        },
    ]
}
